Test
ValidHunters/ExampleMarseyPatch pull request #2
Opened 2023-12-23 18:48 UTC by noverd

2023-12-23 18:48 UTC, noverd commented
Добавил новый патч.

2023-12-23 18:49 UTC, noverd commented
Патч оверлеев

2023-12-24 02:01 UTC, Subversionary requested changes

2023-12-24 02:01 UTC, Subversionary commented on OverlaysPatches/BlindOverlayPatch.cs
> +        }
```suggestion
            Type? BlindOverlay = MarseyPatch.ContentClient.GetType("Content.Client.Eye.Blinding.BlindOverlay");
            if (BlindOverlay != null)
            {
            	MethodInfo? BlindOverlayDraw = BlindOverlay.GetMethod("Draw", BindingFlags.NonPublic | BindingFlags.Instance);
            	if (BlindOverlayDraw != null)
        		yield return BlindOverlayDraw;
            }
        }
```

You should check if that type/method exists, else it will crash by trying to patch a non-existent method.

2023-12-24 02:01 UTC, Subversionary commented on OverlaysPatches/MainPatcher.cs
> +    public static string Description = "Патчит: эффект от космических наркотиков, от опьянения, от слепоты и разрушения зрения сваркой";
Translate to english.

2023-12-24 07:21 UTC, noverd commented on OverlaysPatches/MainPatcher.cs
> +    public static string Description = "Патчит: эффект от космических наркотиков, от опьянения, от слепоты и разрушения зрения сваркой";
Ok.

2023-12-24 08:25 UTC, noverd commented
All done.

2023-12-24 08:35 UTC, noverd commented
Ready to merge

2023-12-24 08:51 UTC, Subversionary requested changes

2023-12-24 08:51 UTC, Subversionary commented on OverlaysPatch/OverlaysPatch.cs
> +	private static bool Postfix(bool value) => false;
Why is this a postfix? You had it as a prefix previously.

2023-12-24 08:54 UTC, noverd commented on OverlaysPatch/OverlaysPatch.cs
> +	private static bool Postfix(bool value) => false;
Oh... Sorry

2023-12-24 08:56 UTC, Subversionary approved these changes

2023-12-24 08:56 UTC, merged